//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogger365.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("283133962923158099")]
        public long BlogIDLuke {
            get {
                return ((long)(this["BlogIDLuke"]));
            }
            set {
                this["BlogIDLuke"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1638114726255085844")]
        public long BlogIDOwen {
            get {
                return ((long)(this["BlogIDOwen"]));
            }
            set {
                this["BlogIDOwen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://picasaweb.google.com/data/feed/api/user/116954792991031607913/albumid/599" +
            "5294768200592849")]
        public string AlbumURILuke {
            get {
                return ((string)(this["AlbumURILuke"]));
            }
            set {
                this["AlbumURILuke"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://picasaweb.google.com/data/feed/api/user/116954792991031607913/albumid/599" +
            "5295239904077553")]
        public string AlbumURIOwen {
            get {
                return ((string)(this["AlbumURIOwen"]));
            }
            set {
                this["AlbumURIOwen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B:\\L")]
        public string ImgDirLuke {
            get {
                return ((string)(this["ImgDirLuke"]));
            }
            set {
                this["ImgDirLuke"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B:\\O")]
        public string ImgDirOwen {
            get {
                return ((string)(this["ImgDirOwen"]));
            }
            set {
                this["ImgDirOwen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B:\\L\\IMG_1419.jpg")]
        public string LastImageLuke {
            get {
                return ((string)(this["LastImageLuke"]));
            }
            set {
                this["LastImageLuke"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B:\\O\\Owen 002.jpg")]
        public string LastImageOwen {
            get {
                return ((string)(this["LastImageOwen"]));
            }
            set {
                this["LastImageOwen"] = value;
            }
        }
    }
}
